# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build

    - name: list what we have
      run: find .
    - name: make sure zip is in dist
      run: ls build/distributions/*.zip
    - name: Upload built jar
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: build/libs/acheditor-*.jar

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs: build

    steps:
    - name: Download built jar
      uses: actions/download-artifact@v2
      with:
        name: jar
    - name: Upload extension to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '*.jar'
